name: lab1_cloud

services:

  db:
    image: postgres:16-alpine
    container_name: lab1_cloud_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: lab1_cloud_app
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSL: ${DB_SSL:-false}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: